name: weather
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  equatable: ^2.0.5
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  geolocator: ^9.0.2
  permission_handler: ^10.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: WeatherIcons
      fonts:
        - asset: assets/fonts/weather-icons-regular.ttf


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"
  min_sdk_android: 16
  web:
    generate: true
    image_path: "assets/icon.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon.jpg"